# Generated by Django 4.2.11 on 2024-08-04 04:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_name', models.CharField(max_length=255)),
                ('course_duration', models.IntegerField()),
                ('course_start_time', models.CharField(max_length=255)),
                ('course_end_time', models.CharField(max_length=255)),
                ('course_level', models.CharField(max_length=255)),
                ('course_requirement', models.TextField()),
                ('course_participant_count', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Instructor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('age', models.IntegerField()),
                ('email', models.EmailField(max_length=255)),
                ('phone', models.CharField(max_length=255)),
                ('gender', models.CharField(max_length=255)),
                ('experience', models.TextField()),
                ('address', models.TextField()),
                ('person_ID', models.CharField(max_length=255)),
                ('skill_set', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('age', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=255)),
                ('phone', models.CharField(max_length=255)),
                ('gender', models.CharField(max_length=255)),
                ('experience', models.TextField()),
                ('address', models.TextField()),
                ('guardian', models.CharField(max_length=255)),
                ('guardian_phone_number', models.CharField(max_length=255)),
                ('person_ID', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Registration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fees_amount', models.IntegerField()),
                ('payment_status', models.BooleanField(default=False)),
                ('course_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='record.course')),
                ('student_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='record.user')),
            ],
        ),
        migrations.AddField(
            model_name='course',
            name='course_instructor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='record.instructor'),
        ),
    ]
